beagledata/urls.py
from django.contrib import admin
from django.urls import path
from myapp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myapp/forms.py
from django.forms import ModelForm
from django import forms
from .models import *
from django.contrib.admin.widgets import  AdminDateWidget, AdminTimeWidget, AdminSplitDateTime
from beagledata import settings

class wifiForm(forms.ModelForm):
    ssid = forms.CharField(required=False)
    password = forms.CharField(required=False)    
    # confirm_password=forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = WifiDetails
        fields = "__all__"
        # fields = ('ssid','password','confirm_password')

    # def clean(self):
    #     cleaned_data = super(wifiForm, self).clean()
    #     password = cleaned_data.get("password")
    #     confirm_password = cleaned_data.get("confirm_password")

    #     if password != confirm_password:
    #         msg = "Password Mismatch Error"
    #         self.add_error('password', msg)
    #         # raise forms.ValidationError(
    #         #     "password and confirm_password does not match"
    #         # )
        
    #     min_length = 8
    #     if len(password) < min_length:
    #         msg = 'Password must be at least %s characters long.' % (str(min_length))
    #         self.add_error('password', msg)
            # raise forms.ValidationError(
            #     "Password must be at least 8 character"
            # )


class DateTimeForm(ModelForm):
    
    class Meta:
        
        model = DateTimeDetails
        fields = "__all__"
        

class LockoutForm(forms.ModelForm):
    weekday_from_1 = forms.IntegerField(required=False,initial=0)
    weekday_to_1 = forms.IntegerField(required=False,initial=0)
    weekday_from_2 = forms.IntegerField(required=False,initial=0)
    weekday_to_2 = forms.IntegerField(required=False,initial=0)

    weekend_from_1 = forms.IntegerField(required=False,initial=0)
    weekend_to_1 = forms.IntegerField(required=False,initial=0)
    weekend_from_2 = forms.IntegerField(required=False,initial=0)
    weekend_to_2 = forms.IntegerField(required=False,initial=0)


    class Meta:
        model = tou_details
        fields = "__all__"


class EcForm(forms.ModelForm):
    sensed_panel_rating = forms.IntegerField(required=False, initial=100)
    c1 = forms.CharField(required=False)
    max_amp1 = forms.IntegerField(required=False,initial=0)
    # c1ab = forms.IntegerField(required=False,initial='A')
    c2 = forms.CharField(required=False)
    max_amp2 = forms.IntegerField(required=False,initial=0)
    # c2ab = forms.IntegerField(required=False,initial='A')
    c3 = forms.CharField(required=False)
    max_amp3 = forms.IntegerField(required=False,initial=0)
    # c3ab = forms.IntegerField(required=False,initial='A')
    c4 = forms.CharField(required=False)
    max_amp4 = forms.IntegerField(required=False,initial=0)
    # c4ab = forms.IntegerField(required=False,initial='A')
    
    class Meta:
        model = ECDetails
        fields = "__all__"

# class CcAssignmentForm(forms.ModelForm):
#     class Meta:
#         model = CcAssignmentDetails
#         fields = "__all__"

templates/index.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/index.css' %}">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>

    <!-- Header -->
    <div class="container-fluid head">
      <img src="{% static 'img/Varian Lite Logo.svg' %}">
    </div>
    <!-- Header -->

    <!-- <img src="{% static 'img/bg.jpg' %}"> -->
  <div class="container-fluid">
   
  <div class="container">
    <form action="" method="post">
      {% csrf_token %}
  <!-- <div id="accordion"> -->
    
    <!-- Wifi Start -->
    <div class="card">
      <div class="card-header" id="headingOne">
        <h5 class="mb-0">
          <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
            Custom Wifi SSID
          </button>
        </h5>
      </div>
    </div>
      <div id="collapseOne" class="collapse " aria-labelledby="headingOne" data-parent="#accordion">
        <div class="card-body">
          <!-- <form action="" method="post">
            {% csrf_token %} -->
            <!-- SSID -->
            <div class="form-group">
              <label for="exampleInputEmail1">SSID</label>
              <input type="text" class="form-control" name="ssid" id="id_ssid" aria-describedby="emailHelp" placeholder="Enter email">
              <small id="emailHelp" class="form-text text-muted">We'll never share your ssid with anyone else.</small>
            </div>

            <!-- passwod and repassword -->
            <div class="form-group">
              <label for="exampleInputPassword1">Password</label>
              <input type="password" class="form-control" name="password" id="exampleInputPassword1" placeholder="Password">
            </div>
            <div class="form-group">
              <label for="exampleInputPassword1">Confirm Password</label>
              <input type="password" class="form-control" name="repassword"  id="exampleInputPassword1" placeholder="RePassword">
            </div>
            <!-- <input type="submit" class="btn btn-info" name="wifi"> -->
          <!-- </form> -->
        </div>
      </div>
    <!-- </div> -->
    <!-- Wifi End -->

    <!-- Date and Time Start -->
    <div class="card">
      <div class="card-header" id="headingTwo">
        <h5 class="mb-0">
          <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
            Date and Time
          </button>
        </h5>
      </div>
      <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
        <div class="card-body">
          <!-- <form action="" method="post">
            {% csrf_token %} -->
            
            <div class="form-group">
              <label for="exampleInputEmail1">Year</label>
              <input type="text" class="form-control" name="year" aria-describedby="emailHelp" placeholder="Enter email">
              <!-- <small id="text" class="form-text text-muted">We'll never share your ssid with anyone else.</small> -->
            </div>
            
            <div class="form-group">  
              <label for="exampleInputPassword1">Month</label>
              <input type="text" class="form-control" name="month" placeholder="Month">
            </div>

            <div class="form-group">
              <label for="exampleInputPassword1">Day</label>
              <input type="text" class="form-control" name="day"  placeholder="Day">
            </div>

            <div class="form-group">
              <label for="exampleInputPassword1">Hour</label>
              <input type="text" class="form-control" name="hour" placeholder="Hour">
            </div>

            <div class="form-group">
              <label for="exampleInputPassword1">Minutes</label>
              <input type="text" class="form-control" name="minute" placeholder="Minute">
            </div>

            <div class="form-group">
              <label for="exampleInputPassword1">AM/PM</label>
              <input type="text" class="form-control" name="am_pm" placeholder="AM/PM">
            </div>

            <div class="form-group">
              <label for="exampleInputPassword1">Time Zone</label>
              <input type="text" class="form-control" name="timezone" placeholder="Time Zone">
            </div>
            <!-- <input type="submit" class="btn btn-info" name="datetime">
          </form> -->
        </div>
      </div>
    </div>
<!-- Date and Time end -->

<!-- Time of use Lockout Start -->
    <div class="card">
      <div class="card-header" id="headingThree">
        <h5 class="mb-0">
          <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
            Time of Use Lockout
          </button>
        </h5>
      </div>
      <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
        <div class="card-body">
          <!-- <form action="" method="post">
            {% csrf_token %} -->
            
            <div class="form-group">
              <label for="exampleInputEmail1">Weekday Hour Range 1</label>
              <input type="text" class="form-control" name="weekday1" aria-describedby="emailHelp" placeholder="Weekday Hour Range 1">
              <!-- <small id="text" class="form-text text-muted">We'll never share your ssid with anyone else.</small> -->
            </div>
            
            <div class="form-group">  
              <label for="exampleInputPassword1">Weekday Hour Range 2</label>
              <input type="text" class="form-control" name="weekday2" placeholder="Weekday Hour Range 2">
            </div>

            <div class="form-group">
              <label for="exampleInputPassword1">Weekend Hour Range 1</label>
              <input type="text" class="form-control" name="weekend1"  placeholder="Weekend Hour Range 1">
            </div>

            <div class="form-group">
              <label for="exampleInputPassword1">Weekend Hour Range 2</label>
              <input type="text" class="form-control" name="weekend2" placeholder="Weekend Hour Range 1">
            </div>

            <!-- <input type="submit" class="btn btn-info" name="lockout">
          </form> -->
        </div>
      </div>
    </div>
<!-- Time of use Lockout End -->

<!-- Electrical Configuration Start -->
    <div class="card">
      <div class="card-header" id="headingFour">
        <h5 class="mb-0">
          <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
            Electrical Configuration
          </button>
        </h5>
      </div>
      <div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordion">
        <div class="card-body">
          <!-- <form action="" method="post">
            {% csrf_token %} -->
            
            <div class="form-group">
              <label for="exampleInputEmail1">Sensed Panel Rating</label>
              <input type="text" class="form-control" name="sensed_panel_rating" aria-describedby="emailHelp" placeholder="Sensed Panel Rating">
              <!-- <small id="text" class="form-text text-muted">We'll never share your ssid with anyone else.</small> -->
            </div>
            
            <div class="form-group">  
              <label for="exampleInputPassword1">Sensor CT Rating</label>
              <input type="text" class="form-control" name="sensor_ct_rating" placeholder="Sensor CT Rating">
            </div>

            <div class="form-group">
              <label for="exampleInputPassword1">Circuit Breaker A</label>
              <input type="text" class="form-control" name="circuit_breaker_a"  placeholder="Circuit Breaker A">
            </div>

            <div class="form-group">
              <label for="exampleInputPassword1">Circuit Breaker B</label>
              <input type="text" class="form-control" name="circuit_breaker_b" placeholder="Circuit Breaker B">
            </div>

            <!-- <input type="submit" class="btn btn-info" name="ec">
          </form> -->
        </div>
      </div>
    </div>
    <!-- Electrical Configuration End -->

    <!-- Charger Circuit Assignment Start -->
    <div class="card">
      <div class="card-header" id="headingFive">
        <h5 class="mb-0">
          <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
            Charger Circuit Assignment
          </button>
        </h5>
      </div>
      <div id="collapseFive" class="collapse" aria-labelledby="headingFive" data-parent="#accordion">
        <div class="card-body">
          <!-- <form action="" method="post">
            {% csrf_token %} -->
            
            <div class="form-group">
              <label for="exampleInputEmail1">Charger 1</label>
              <input type="text" class="form-control" name="c1" aria-describedby="emailHelp" placeholder="Charger 1">
              <!-- <small id="text" class="form-text text-muted">We'll never share your ssid with anyone else.</small> -->
            </div>
            
            <div class="form-group">  
              <label for="exampleInputPassword1">Circuit1 A/B</label>
              <input type="text" class="form-control" name="c1ab" placeholder="Circuit A/B">
            </div>

            <div class="form-group">
              <label for="exampleInputPassword1">Charger 2</label>
              <input type="text" class="form-control" name="c2"  placeholder="Charger 2">
            </div>

            <div class="form-group">
              <label for="exampleInputPassword1">Circuit2 A/B</label>
              <input type="text" class="form-control" name="c2ab" placeholder="Circuit2 A/B">
            </div>

            <div class="form-group">
              <label for="exampleInputEmail1">Charger 3</label>
              <input type="text" class="form-control" name="c3" aria-describedby="emailHelp" placeholder="Charger 3">
              <!-- <small id="text" class="form-text text-muted">We'll never share your ssid with anyone else.</small> -->
            </div>

            <div class="form-group">  
              <label for="exampleInputPassword1">Circuit3 A/B</label>
              <input type="text" class="form-control" name="c3ab" placeholder="Circuit3 A/B">
            </div>

            <div class="form-group">
              <label for="exampleInputPassword1">Charger 4</label>
              <input type="text" class="form-control" name="c4"  placeholder="Charger 4">
            </div>

            <div class="form-group">
              <label for="exampleInputPassword1">Circuit4 A/B</label>
              <input type="text" class="form-control" name="c4ab" placeholder="Circuit4 A/B">
            </div>

            <!-- <input type="submit" class="btn btn-info" name="cca">
          </form> -->
        </div>
      </div>
    </div>
    <!-- Charger Circuit Assignment End -->
    <input type="submit" class="btn btn-info">
          </form>
  </div>
 
</div>
</body>
</html>